services:
  app:
    image: bloglist-frontend
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - '3000:3000'
    container_name: bloglist-frontend
    depends_on:
      - server

  server:
    image: bloglist-backend
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/usr/src/app
    ports:
      - '3003:3003'
    container_name: bloglist-backend